### PR TITLE
import from gir

### PR DESCRIPTION
**Pull request by vhdirk**
These is what gir currently generates. Most pressing issues:
- [ ] to/from glib conversion in trampolines
- [x] correct crate/module names
- [ ] interfaces
- [x] import of user-defined code blocks (e.g. gapplication)

### CODE REVIEW

**Comment by sdroege** [comment]
Thanks!

**Comment by sdroege** [comment]
Let's maybe start with the ones we already have instead of adding a million other types at once :) That makes it easier to review

**Comment by vhdirk** [comment]
Sure. I'll start with gapplication then. But the interfaces would be more interesting to me, since I cannot wrap my head around how to do those :)

**Comment by sdroege** [comment]
For the interfaces, maybe start writing one by hand in another PR and then we go over it together :) Doing it manually first is probably better than starting with the code generation. `GInputStream` seems to be a relatively simple interface for example, or `GOutputStream`

**Comment by vhdirk** [comment]
But GInputStream isn't an interface?

**Comment by sdroege** [comment]
Indeed, neither is. Ignore me, sorry :)

**Comment by vhdirk** [comment]
No problem. Nevertheless I can make a separate PR for every single object generated with gir. I would assume that the subclass PR needs a lot of work before getting accepted. Adding them one by one here, starting from the generated output will allow me to use that at least.

**Comment by sdroege** [comment]
Sounds like a good plan :) Let's first start with the existing ones, and then we can go through them one by one.

I'd like to have them separately so that it's less to review at once, and to make sure I don't miss any accidental unsafeties.

**Comment by vhdirk** [comment]
Though starting with gapplication, while making the gir more stable, will be less valuable to me since we already have that one...

**Comment by sdroege** [comment]
ok, then start with a new one :) I thought starting with an existing one would help validating that the generated code makes sense structurally by seeing the diffs

**Comment by sdroege** [comment]
Should we close this one and handle it all in new PRs, one by one?

**Comment by vhdirk** [comment]
Yes. I forgot that this one was still open

**Pull request closed without merging**
